using System;
using System.Collections.Generic;
using System.Text;

namespace Volunesia.Models
{
    public class Nonprofit
    {
        //The identification number that can be either autogenerated or the EIN of non-school organizations
        public string    NonprofitID   { get; set; }
        //The name of the nonprofit
        public string NonprofitName { get; set; }
        //What kind of nonprofit is this 
        public string NonprofitType { get; set; }
        //The person in charge of the account
        public NonprofitRepresentative PrimaryRepresentative { get; set; }
        //The main number to contact regarding events
        public string DefaultPhone  { get; set; }
        //The primary location of the nonprofit
        public string ZipCode       { get; set; }
        //City where the nonprofit is located in
        public string City { get; set; }
        //State where the nonprofit is located in
        public string State { get; set; }
        //Image path for nonprofit (possible logo or team photo)
        public string ImagePath { get; set; }
        //The nonprofit's mission statement
        public string MissionStatement { get; set; }
    }
}
