using System;
using System.Collections.Generic;
using System.Text;

namespace Volunesia.Models
{
    public class Nonprofit
    {
        //The identification number that can be either autogenerated or the EIN of non-school organizations
        public string    NonprofitID   { get; set; }
        //The name of the nonprofit
        public string NonprofitName { get; set; }
        //What kind of nonprofit is this 
        public string NonprofitType { get; set; }
        //The person in charge of the account
        public NonprofitRepresentative PrimaryRepresentative { get; set; }
        //The main number to contact regarding events
        public string DefaultPhone  { get; set; }
        //The primary location of the nonprofit
        public string ZipCode       { get; set; }
    }
}
